// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "DroidController",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "DroidController",
            targets: ["AppModule"],
            bundleIdentifier: "hcrane.droid.controller",
            teamIdentifier: "R82WJ5W3TV",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .pencil),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .bluetoothAlways(purposeString: "Unknown Usage Description")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/manolofdez/AsyncBluetooth", "1.3.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "AsyncBluetooth", package: "AsyncBluetooth")
            ],
            path: ".",
            exclude: ["README.md", "LICENSE"]
        )
    ]
)
